#!/usr/bin/env bash
# Fetch PP-OCRv4 inference models + Chinese charset.
# Usage: bash download_models.sh [dest_dir]
# Default dest: <repo_root>/models/paddle_ocr
set -euo pipefail
DEST="${1:-$(cd "$(dirname "$0")"/../.. && pwd)/models/paddle_ocr}"
mkdir -p "$DEST"
cd "$DEST"

# Each tarball expands to a directory named after the model.
declare -A MODELS=(
  ["ch_PP-OCRv4_det_infer"]="https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar"
  ["ch_ppocr_mobile_v2.0_cls_infer"]="https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar"
  ["ch_PP-OCRv4_rec_infer"]="https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_infer.tar"
)

for name in "${!MODELS[@]}"; do
  if [[ -d "$name" && -f "$name/inference.pdmodel" ]]; then
    echo "[skip] $name already present"
    continue
  fi
  url="${MODELS[$name]}"
  echo "[fetch] $name <- $url"
  wget -q --show-progress "$url" -O "${name}.tar"
  tar -xf "${name}.tar"
  rm -f "${name}.tar"
done

if [[ ! -f ppocr_keys_v1.txt ]]; then
  echo "[fetch] ppocr_keys_v1.txt"
  wget -q --show-progress \
    https://raw.githubusercontent.com/PaddlePaddle/PaddleOCR/main/ppocr/utils/ppocr_keys_v1.txt
fi

# Write per-model paddle_inference virtual-flowunit TOMLs so each model dir is
# a self-contained ModelBox driver directory. The graph references the flowunit
# by the [base].name set here. Hyphens and dots are illegal in flowunit names
# (graphviz lexer balks), so we sanitise the cls dir name to underscores.
write_model_toml() {
  local subdir="$1"
  local fu_name="$2"
  local model="$3"
  local params="$4"
  local in_port="$5"
  local out_port="$6"
  local desc="$7"
  cat > "$DEST/$subdir/$fu_name.toml" <<EOF
# Auto-generated by examples/paddle_ocr/download_models.sh.
# Virtual flowunit TOML describing this Paddle inference model so ModelBox can
# instantiate it from a graph node. The graph references flowunit="$fu_name".
[base]
name        = "$fu_name"
device      = "cuda"
version     = "1.0.0"
description = "$desc"
entry       = "./$model"
type        = "inference"
virtual_type = "paddle"
group_type  = "Inference"

[config]
model_file  = "./$model"
params_file = "./$params"
# Leave input_name / output_name empty to use the names Paddle ships with the
# model. Override (e.g. input_name = ["x"]) if your export reports different names.
# input_name  = ["$in_port"]
# output_name = ["$out_port"]

[input]
[input.input1]
name = "$in_port"
type = "float"

[output]
[output.output1]
name = "$out_port"
type = "float"
EOF
}

write_model_toml ch_PP-OCRv4_det_infer            ch_PP-OCRv4_det_infer            inference.pdmodel inference.pdiparams x "sigmoid_0.tmp_0" "PP-OCRv4 text detector"
write_model_toml ch_ppocr_mobile_v2.0_cls_infer   ch_ppocr_mobile_v2_0_cls_infer   inference.pdmodel inference.pdiparams x "softmax_0.tmp_0" "PP-OCR text-direction classifier"
write_model_toml ch_PP-OCRv4_rec_infer            ch_PP-OCRv4_rec_infer            inference.pdmodel inference.pdiparams x "softmax_5.tmp_0" "PP-OCRv4 text recogniser"

echo
echo "Models ready in $DEST:"
ls -la "$DEST"
